phases:
  - name: "Initialization"
    steps:
      - session: json-placeholder
        request:
          method: GET
          endpoint: "/users"
          headers:
            Accept: "application/json"
        store:
          - var: "users"
            query: "map(.id)"
        retry:
          max_retries: 3
          backoff_factor: 1.0
          timeout: 10
        validate_ssl: true
        on_error: abort

  - name: "Fetch User Details"
    parallel: true
    steps:
      - session: json-placeholder
        iterate: "user_id in users"
        request:
          method: GET
          endpoint: "/users/{user_id}"
          params:
            details: "full"
        store:
          - var: "user_{user_id}_details"
            query: "."
        retry:
          max_retries: 2
          backoff_factor: 0.5
          timeout: 5
        validate_ssl: true
        on_error: abort

  - name: "Create Posts"
    parallel: true
    steps:
      - session: json-placeholder
        iterate: "user_id in users"
        request:
          method: POST
          endpoint: "/posts"
          data:
            title: "Post by user {user_id}"
            body: "This is a test post for user {user_id}."
            userId: "{user_id}"
        store:
          - var: "post_{user_id}_id"
            query: ".id"
        retry:
          max_retries: 3
          backoff_factor: 1.0
          timeout: 10
        validate_ssl: true
        on_error: ignore
