name: Publish RestBook

on:
  push:
    branches:
      - main
      - feat-add-github-publish-workflow

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: '2.1.1'  # Specify the Poetry version if needed

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        if: github.event_name == 'push'
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: failure()
